### PR TITLE
implementing soft_checks for #620

### PR DESCRIPTION
**Pull request by noahwsmith**
## Link to Github issue or other discussion

Solution for https://github.com/mjordan/islandora_workbench/issues/620
Refactors work in progress from #268 to use new `perform_soft_checks` variable

## What does this PR do?

Allows `soft_checks` for `--check` errors that should really be handled in batches, rather than having the check fail on every instance. Initial implementation includes:
* Parent/child order issues
* File extension checks
* EDTF date validation

And it refactors the old `strict_check` to now use `perform_soft_checks`. The logic for variable checking has been reversed, since semantically the two config variables mean the opposite.

## What changes were made?

* Added a new config `'perform_soft_checks': True`
* Added three uses of that variable to allow skipping `exit` functions 
* Refactors `strict_check` to `perform_soft_checks`

## How to test / verify this PR?

* Check out this branch and run a test ingest which includes the three described error types. You should get log messages but your `--check` run should not stop and it should behave like it did with `strict_check` being false.
* On this branch, change `'perform_soft_checks': True,` to `'perform_soft_checks': False,` and run a test ingest which includes the three described error types. You should get the `strict_check` true behavior. 

## Interested Parties

@mjordan, @McFateM, @dara2

### CODE REVIEW

**Comment by mjordan** [comment]
Works as advertised, but `--check`'s output is now very misleading:

```
OK, connection to Drupal at https://islandora.traefik.me verified.
"nodes_only" option in effect. Media files will not be checked/validated.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file input_data/pr_637.csv found.
OK, all 3 rows in the CSV file have the same number of columns as there are headers (5).
OK, CSV column headers match Drupal field names.
OK, required Drupal fields are present in the CSV file.
OK, EDTF field values in the CSV file validate.
OK, term IDs/names in CSV file exist in their respective taxonomies.
Configuration and input data appear to be valid.
```

I think we need to add another entry to the output if `perform_soft_checks` is true to say something like:

```
OK, connection to Drupal at https://islandora.traefik.me verified.
"nodes_only" option in effect. Media files will not be checked/validated.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file input_data/pr_637.csv found.
OK, all 3 rows in the CSV file have the same number of columns as there are headers (5).
OK, CSV column headers match Drupal field names.
OK, required Drupal fields are present in the CSV file.
OK, EDTF field values in the CSV file validate.
OK, term IDs/names in CSV file exist in their respective taxonomies.
Configuration and input data appear to be valid.
Warning: "perform_soft_checks" is enabled so you need to review your log for errors despite the "OK" reports above.
```

If you agree, I'll open a discussion on slack to get broader input. This is a very big (and welcome) change that could have catastrophic impact if not understood by users!

**Comment by dara2** [comment]
I really like that suggestion. It's a good reminder because sometimes I forget that now with strict_check set to "false".

**Comment by noahwsmith** [comment]
Sounds great to me too!

**Comment by noahwsmith** [comment]
I get three hits in the utils file for `print("Configuration and input data appear to be valid.")` - which one(s) need the extra disclaimer?

**Comment by mjordan** [comment]
I think putting it at https://github.com/mjordan/islandora_workbench/blob/main/workbench_utils.py#L1420 is OK, something like:

```python
if config['perform_soft_checks'] is True:
    print('Warning: "perform_soft_checks" is enabled so you need to review your log for errors despite the "OK" reports above.')
```

**Comment by noahwsmith** [comment]
Perfect, I pushed that change. We'll await community feedback, now!

**Comment by noahwsmith** [comment]
Based on feedback in Slack: https://islandora.slack.com/archives/C01TLCB0EEQ/p1689178199878639 

I have reversed the behavior here to be `'perform_soft_checks': False` so we don't disrupt any current usage of Workbench.

**Comment by mjordan** [comment]
Thanks @noahwsmith! I'll document this new setting.

**Pull request merged**
