### PR TITLE
Add Dockerfile as an option to run

### PR DESCRIPTION
**Pull request by DonRichards**
Adding this so I don't forget. 
This is a Dockerfile to allow the Python dependencies to be isolated into a single container to run. 

This should simplify the running but needs work and documentation.

### CODE REVIEW

**Comment by mjordan** [comment]
Very cool, thanks @DonRichards! Am looking forward to kicking the tires.

**Comment by DonRichards** [comment]
@mjordan OK, this "should" be super simple (that was the goal). I left the command structure in place so that it's easier to see where the local and container cross and so that if workbench ever change's its command structure it won't impact the docker file. 

```shell
# Build the container
$ docker build -t workbench-docker .

# Run it
$ docker run -it --rm --name my-running-workbench workbench-docker bash -lc "(./workbench --config hackdoc_demo.yml --check)"
```

These 2 command lines were noted as a code comments within the Dockerfile and a "feature" was added to the README but documentation is somewhere else so I assume that would be up to you.

**Comment by emudojo** [comment]
thanks @DonRichards I would rather have and ENTRYPOINT defined as you can easily just do

docker run -it --rm workbench-docker/xyz hackdoc_demo.yml

see example here on how to use it https://github.com/driebit/docker-node-gulp
and some docs https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#entrypoint

**Comment by DonRichards** [comment]
@emudojo That's a great idea! Thanks, I'll try that.

**Comment by mjordan** [comment]
@DonRichards just taking this for a quick test drive and I think you forgot to `git add` the Dockerfile. Can you check?

**Comment by DonRichards** [comment]
@mjordan  It's showing up on Github. Do you not see it when you click on "File Changed" tab at the top? https://github.com/mjordan/islandora_workbench/pull/233/files

**Comment by DonRichards** [comment]
@emudojo I don't know much about entry point but looks like it's adding complexity by adding another file (bash file) to accomplish the same thing. What benefits are there with moving the functionality to an entry point?

**Comment by mjordan** [comment]
@DonRichards sorry, my mistake, I checked out your `issue-227` branch. I should be been in your `main` branch. Sorry!

**Comment by DonRichards** [comment]
I've done that before.

**Comment by DonRichards** [comment]
@mjordan this should be completely testable in its current state. I'm not sure if I can invest much more time making the changes Herzel is suggesting right now. But as it sits, it should work on any environment that has docker installed.

**Comment by mjordan** [comment]
Giving this a try now. Building the image worked fine, but when I run

```
docker run -it --rm --name my-running-workbench workbench-docker bash -lc "(./workbench --config create.yml --check)"
```
I get the following error from Workbench:

```
Error: Workbench cannot connect to http://localhost:8000. Please verify the "host" setting in your configuration and check your network connection.
```
Running `docker run -it --rm --name my-running-workbench workbench-docker bash -lc "(ping localhost)"` returns the expected `ping` output, so networking is fine.

Running `./workbench --config create.yml --check` outside of Docker behaves as I expect it to. My configuration file looks like this:

```
task: create
host: "http://localhost:8000"
username: admin
password: islandora
```

Any thoughts?

**Comment by DonRichards** [comment]
Would you mind replacing localhost with host.docker.internal and see what happens?

**Comment by DonRichards** [comment]
Something like this either with or without the http protocol

```yml
task: create
host: "host.docker.internal:8000"
username: admin
password: islandora
```

**Comment by DonRichards** [comment]
I tested it on ISLE's "https://islandora.traefik.me/" but not the default install.

**Comment by mjordan** [comment]
Thanks, Sadly I have not been successful in standing up isle-dc so can't test it, but will test host.docker.internal:8000. If that solve is, we can document it.

**Comment by DonRichards** [comment]
Try this
`docker build --network="host" -t workbench-docker .`

**Comment by DonRichards** [comment]
Another option might be 

for windows : host: 
`"docker.for.win.localhost:8000"`

for mac : host: 
`"docker.for.mac.localhost:8000"`

**Comment by mjordan** [comment]
Not having much luck. I've removed the workbench-docker image and run `docker build --network="host" -t workbench-docker .`, which barfs some errors (the most dire of which is `warning: install_lib: 'build/lib' does not exist -- no Python modules to install`) but results in the same response from Workbench as above,  when using `http://localhost:8000`, `host.docker.internal:8000`, and `docker.for.linux.localhost`.

**Comment by DonRichards** [comment]
@mjordan I think I found it. Host needed to be wrapped in double quotes. 
`docker run -it --rm --network="host" --name my-running-workbench workbench-docker bash -lc "(./workbench --config hackdoc.yml --check)"`

This basically allows the container to interact as though it was running python from you desktop. It gives it all of your localhost loopbacks and normal network access.

**Comment by DonRichards** [comment]
I pushed the updated code comment to reflect this.

**Comment by mjordan** [comment]
Sorry, still not seeing what you are. Running at your latest commit (8d9f2f4ad5413a8449f1c6447646a81497e4021b), with this config file:

```
task: create
host: "http://localhost:8000"
username: admin
password: islandora
```
I rebuilt the image and ran this:

```
docker run -it --rm --network="host" --name my-running-workbench workbench-docker bash -lc "(./workbench --config dockertest.yml --check)"
```

and am getting a networking (via `requests`) exception: 

```
requests.exceptions.InvalidSchema: No connection adapters were found for 'docker.for.linux.localhost:8000/islandora_workbench_integration/upload_max_filesize'
```

https://docs.docker.com/network/network-tutorial-host/ shows that `host` is not in quotes. However, when I run it as shown on that page, I get the same exception as I do running it with --network="host".

Also, https://docs.docker.com/network/host/ says that "The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server.", but I'm probably misinterpreting what that means. *You're* on a Mac and *I'm* on Linux.

**Comment by DonRichards** [comment]
@mjordan I've been testing this on both Mac and Linux. I don't have anything running locally on my Mac so I've been pointing it at the test site you setup and only running "-check". 

1. So if in linux add **--network="host"** and that should work. 
2. If in a MAC, change the YML
```yaml
# From
...
host: "http://localhost:8000"
...
# To
...
host: "http://host.docker.internal:8000"
...
```
3. If in Windows use previous instructions (possibly, I don't know. I can't test on Windows).

Basically to test this communication quickly I ran a python web-server on port 8000 `$ python -m http.server 8000` and then running a docker containers and curl port 8000 for a response. 
```shell 
$ docker run --rm -it alpine sh
$ apk add curl
$ curl http://host.docker.internal:8000
...
</html>

$ exit
```

This seems to work with a Mac to communicate. I don't have playbook running locally to fully to though.

**Comment by mjordan** [comment]
@DonRichards by "the test site you setup" do you mean the one we used for the Hack/Doc? If so I'll try that later today. 

In order to eliminate my docker setup (I'm also unable to get isle-dc working), or PECKAC errors, I think we should get someone else to test it. @dannylamb, would you be able to test this some time in the next couple days?

**Comment by DonRichards** [comment]
I updated the code comments to reflect my last suggestions.

**Comment by DonRichards** [comment]
This copies `ADD ./` the migration files into the container. This could bloat the container quickly and requires a rebuild upon any changes. I'll add a quick change as soon as I can to mount a directory instead of copying all of the contents. This means there is no need to rebuild with every change.

**Comment by DonRichards** [comment]
OK, this works now without copying the files into the container. This mounts the directory within the container and it should work. Again, I don't have the ability to check localhost but this should work universally. I can remove the 'filemagic' install if that helps

**Comment by mjordan** [comment]
@DonRichards catching up on this. My container built successfully, but I'm getting a "No such file" error as shown here:

```
docker run -it --rm --network="host" --name my-running-workbench workbench-docker bash -lc "(./workbench --config create.yml --check)"
bash: ./workbench: No such file or directory
```
I can confirm, however, that executing `python` in the container works:

```
docker run -it --rm --network="host" --name my-running-workbench workbench-docker bash -lc "(python)"
Python 3.9.2 (default, Feb 19 2021, 17:11:58) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by DonRichards** [comment]
I wonder if this would work
```shell
docker run -it --rm --network="host" --name my-running-workbench workbench-docker bash -lc "(python workbench --config create.yml --check)"
```

**Comment by DonRichards** [comment]
This change is currently working in the isle-dc build. It uses these commands to build and run it from the makefile
```shell
	[ -d "islandora_workbench" ] || (git clone -b staging --single-branch https://github.com/DonRichards/islandora_workbench)
	sed -i 's/^nopassword.*/password\: $(shell cat secrets/live/DRUPAL_DEFAULT_ACCOUNT_PASSWORD) /g' islandora_workbench/demoBDcreate*
	sed -i  's/http:/https:/g' islandora_workbench/demoBDcreate*
	sed -i  's/author_email\="mjordan@sfu"\,$$/author_email="mjordan@sfu", packages=["i7Import", "i8demo_BD", "input_data"],/g' islandora_workbench/setup.py
	cd islandora_workbench && docker build -t workbench-docker .
	cd islandora_workbench && docker run -it --rm --network="host" -v $(shell pwd)/islandora_workbench:/workbench --name my-running-workbench workbench-docker bash -lc "(cd /workbench && python setup.py install 2>&1 && ./workbench --config demoBDcreate_all_localhost.yml)"`
```
The i8demo_BD migration doesn't exist here, but this should show how it works and what is being done to get it to like the migrations.

**Comment by mjordan** [comment]
@DonRichards success! Running a clean `sudo make demo` installs workbench as expected and the sample objects are ingested. I'll merge.

One thing though is that no collections are listed on the Drupal homepage. I don't think that is related to the workbench change though.

I'll merge this into my main branch.

**Comment by DonRichards** [comment]
Yeah, it's an issue with isle. I thought it was fixed. If you go into the view and under the "Browse All Collections" tab remove the filter criteria `(field_resource_type: Taxonomy term) Taxonomy term: External URI:uri (= http://purl.org/dc/dcmitype/Collection)` and click save. I'm going to see if I can just add that as a PR now to get it in so people will stop having to do this.

**Pull request merged**
