### PR TITLE
Change references to ./islandora_workbench

### PR DESCRIPTION
**Pull request by dara2**
Suggested update to directory name for workbench, to match default directory name on install.

### CODE REVIEW

**Comment by mjordan** [comment]
@dara2 I've renamed the `master` branch to `main` (and deleted `master`, and doing this automatically closed your PR since it was against `master`.

I agree that it's a good idea to name the script `islandora_workbench` rather than `workbench`. However, doing so without letting users know may be confusing. Let me start a conversation in Slack to warn people, and then I'll take care of renaming it and give you credit. Sound OK?

**Comment by dara2** [comment]
Hi @mjordan - It seemed the directory was already named `islandora_workbench`. When I tried to follow the instructions to look for `workbench`, there was no such directory. What I had instead was `islandora_workbench`. So I wanted to suggest updating the references to that directory in the instructions (whereas I see the script itself is still called `workbench`). I may have gotten too overzealous in my suggested edits though! Happy to discuss more in Slack!

**Comment by mjordan** [comment]
Thanks for the extra context. Can you take a look at the "Usage" section of https://mjordan.github.io/islandora_workbench_docs/ and at the "Installation" section of https://mjordan.github.io/islandora_workbench_docs/installation/ to see if that addresses the issue? If not, let me know if you have any suggestions.

**Comment by mjordan** [comment]
Also, I'd love to hear if you have any other suggestions for making Islandora Workbench easier to use or more useful!

**Pull request closed without merging**
