### PR TITLE
Draft: Example content naming

### PR DESCRIPTION
**Pull request by DonRichards**
## Link to Github issue or other discussion

https://github.com/mjordan/islandora_workbench/issues/537

## What does this PR do?

Add the demo content . I think it may have an issue with collections, and putting the content with its parent object.

## What changes were made?

Adds a config file, a directory full of files including a CSV that references the media files within the directory.

## How to test / verify this PR?

Open isle-dc and run the migration. There are a few steps needed. Please see https://github.com/Islandora-Devops/isle-dc/blob/development/Makefile#L372-L385

## Interested Parties

@mjordan 

---

## Checklist

* [ ] Have you run `pycodestyle --show-source --show-pep8 --ignore=E402,W504 --max-line-length=200 yourfile.py`? 
* [X] Have you included same configuration and/or CSV files useful for testing this PR?
* [ ] Have you written unit or integration tests if applicable?
* [X] If the changes in this PR require an additional Python library, have you included it in `setup.py`?
* [ ] If the changes in this PR add a new configuration option, have you provided a default for when the option is not present in the .yml file?

I'm not sure how much of this applies.

### CODE REVIEW

**Comment by mjordan** [comment]
@DonRichards I'm not crazy about adding 75 megs of sample data to the workbench git repo for non-ISLE users. Can we host the sample content in a separate repo and have the ISLE build scripts clone it separately? Would probably take only a single change to the workbench config files to point to the sample data input_dir.

**Comment by DonRichards** [comment]
@mjordan I created this https://github.com/DonRichards/islandora_workbench_demo_content
What do you think? Thoughts?

**Comment by mjordan** [comment]
Super, I'll give it a spin this evening.

**Comment by DonRichards** [comment]
I can't get the rollback to work as expected. 
`Error: If the "Standalone media URL" option at https://islandora.traefik.me/admin/config/media/media-settings is unchecked, clear your Drupal cache and run Workbench again.` but it isn't checked and I've cleared the cache

**Pull request closed without merging**
