### PR TITLE
First attempt at adding unit tests to WorkbenchConfig.py [WIP]

### PR DESCRIPTION
**Pull request by ysuarez**
## Link to Github issue or other discussion

#445 

## What does this PR do?

Adds a few unit tests using the Python built-in`unittest` module to WorkbenchConfig.py

## What changes were made?

New unit test file added called `tests/unit_tests_workbench_config.py` but it may make sense to integrate the unit tests into a pre-existing existing unitest file. 

Also added some test config.yml files in:
tests/assets/WorkbenchConfig_test

There might be a better approach to test WorkbenchConfig.py that having several different config files, but this seems like a good starting point. We may want to come up with a standardized way to name the test config files.

## How to test / verify this PR?

Write now my unittest code works with this execution syntax:
 
python3 -m unittest -v tests/unit_tests_workbench_config.py

NOTE:  I will make changes so that in the future my test(s) works with the syntax used for other isladnora_workbench tests. I am using this as an experiment to learn Python and unittest module best practices.

## Interested Parties

@mjordan

---

## Checklist

* [x] Before opening this PR, have you opened an issue explaining what you want to to do?
* [x] Have you run `pycodestyle --show-source --show-pep8 --ignore=E402,W504 --max-line-length=200 yourfile.py`? 
* [x] Have you included some configuration and/or CSV files useful for testing this PR?
* [ ] Have you written unit or integration tests if applicable?
* [ ] Does the code added in this PR require a version of Python that is higher than the current minimum version?
* [ ] If the changes in this PR require an additional Python library, have you included it in `setup.py`?
* [ ] If the changes in this PR add a new configuration option, have you provided a default for when the option is not present in the .yml file?

### CODE REVIEW

**Comment by ysuarez** [comment]
@mjordan, here is my first attempt at writing unittest style unit tests, also my first attempt writing a unit test for a class.

This is still a work in progress, and I suspect you may want me to change some or a lot of my approach. 

For example, I did some light research on writing unit tests on classes, and it is not considered a best practice to test private methods of a class. (Of course there are always exceptions to that best practice.) Currently all of the methods of the WorkbenchConfig class are public (by several definitions[1]), but a few could be considered utility methods that perhaps we should not try to test individually? 

Do you have preference in what methods I try to test? 

In my light research it was encouraged to only test "public" class methods, and `get_configs()` would be a good starting candidate for unit testing. Right now my PR shows a few tests that targeted some methods I would consider "utility" methods, but I may not stick to that approach and just test through get_config(). At least I got a chance to try out unittest "mocking" in testing the utility methods.

At this point I am planning to just create several test config.yml files to induce success or failure conditions that I can test with unit tests. How does that sound?

Thoughts?

[1] Python does not currently have a way enforce that a class method be private, the current Python convention is to prefix the name of a method with underscore to show a programmer's intention.

**Comment by ysuarez** [comment]
Forgot to mention that for me all tests are passing, but at least in `test_init_validate_invalid_mutators_01()` and `test_init_validate_invalid_mutators_02()" I am currently unable to verify what error message string `sys.exit()` is being called with. That way I can verify that appropriate error condition was detected. I may just need to find the correct syntax to use.

**Comment by ysuarez** [comment]
@mjordan I was able to solve the issue I had with properly checking the message passed to `sys.exit()` by using `assertRaisesRegex`

Also, I think I am ready for a first round of feedback and suggestions from you on my current WIP. 

For example...
* Which class methods to test directly, or should I only test through the `get_confids()` since that is the most "public" method via passing various specially crafted config files. 
    * Right now one of the things I am doing is that I am indirectly testing the logic inside of `__init__()` by creating a new WorkbenchConfig object and testing calls to `sys.exit()`.
* Also, any config file edge cases you would like me to focus on?  I am currently testing for invalid path to a config .yml file, and config files that set more than one "mutator."
* Suggestions on how I name test methods and test config files?

We can do it on Slack, Zoom, or just here on Github.

Thanks in advance

**Comment by mjordan** [comment]
@ysuarez thanks, this all looks good to me. When I run `python -m unittest -v tests/unit_tests_workbench_config.py` all tests pass.

However, when I run `python tests/unit_tests_workbench_config.py`, I get the following error:

```
raceback (most recent call last):
  File "/home/mark/hacking/islandora_workbench/tests/unit_tests_workbench_config.py", line 5, in <module>
    from WorkbenchConfig import WorkbenchConfig
ModuleNotFoundError: No module named 'WorkbenchConfig'
```

Running unittest as a module is what https://docs.python.org/3/library/unittest.html recommends, and the other tests suites run perfectly fine using that method, do maybe we shouldn't worry about the import error when running `python tests/unit_tests_workbench_config.py`. I will update the docs accordingly.

**Comment by ysuarez** [comment]
@mjordan I can look into making this very common syntax work...
`python tests/unit_tests_workbench_config.py`

I was just delaying that work because I wanted to avoid some common issues with import paths that I knew in the short term I could eliminate by using `python3 -m unittest xyz`. The previous syntax really helps with "automatic test discovery" in pytests and looks like in `unittest` too. (In case when you need a workaround when having momentary path issues in the future.)

I will next work on making this test run like the others, and my next step is to add this syntax which is definitely needed (but more could be needed too).

```
if __name__ == '__main__':
    unittest.main()
```

Therefore don't change the docs for now.

**Comment by ysuarez** [comment]
@mjordan I think the test file should run as a standalone script now. It does for me, but YMMV. 

As I suspected I had to add... 

```
if __name__ == '__main__':
    unittest.main()
```

but I also had to add... 

```
import os
import sys
```


```
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from WorkbenchConfig import WorkbenchConfig
```

This path part above does not seem very "pythonic," but it works and is probably related by some of the path quirks Python has.

This is why when researching pytest for a presentation and own use(and now unittest), I was glad to figure out that if I explicitly call the unittest module by name I really don't have import path issues.

Therefore I use:
`python3 -m pytest xyz.py`
`python3 -m unittest xyz.py`

and I don't have to use...
```
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from WorkbenchConfig import WorkbenchConfig
```

I say we stick to the way you are doing it for now. I can then report back if I am ready to endorse a different way to run the tests than...

`python tests/unit_tests_workbench_config.py`

**Comment by mjordan** [comment]
Thanks! `python tests/unit_tests_workbench_config.py` now runs.

**Comment by mjordan** [comment]
@ysuarez I can merge this at any time, and we can open further PRs. I'll be out of office  Sept 14 - 18 so might be good to get this in.

**Comment by ysuarez** [comment]
Then go ahead and merge this in now, and I will make more PRs going forward. 

I will turn this into regular (non-draft) PR.

**Pull request merged**
