### PR TITLE
Addressing compatibility and remove DOCKER_BUILDKIT in the Docker setup

### PR DESCRIPTION
**Pull request by DonRichards**
## Link to Github issue or other discussion

> [Issue #814](https://github.com/mjordan/islandora_workbench/issues/814) - Improve Dockerfile to Handle Permissions (run as non-root user) and Enhance Build Compatibility.
> [PR #18](https://github.com/mjordan/islandora_workbench_docs/pull/18) - Add docs for using Dockerfile

## What does this PR do?

> This PR enhances the existing Dockerfile by addressing build warning issues that were confusing when running building the container. It also optimizes the build process and improves compatibility with different host environments by aligning user and group IDs inside the container with those on the host system.

## What changes were made?

> - **User and Group ID Handling**: Introduced build arguments `USER_ID` and `GROUP_ID` to ensure the Docker container runs with the same user and group IDs as the host, preventing permission issues when mounting directories.
> - **Permission Management**: Added steps to create a group with the specified `GROUP_ID` and set proper ownership for the `/workbench` directory inside the container.
> - **Environment Variable Update**: Added the `.local/bin` directory to the `PATH` to ensure that the scripts installed by `pip` are accessible.
> - **DOCKER_BUILDKIT=0**: Removed the need for most situations.

## How to test / verify this PR?

1. **Build the Docker Image**: Run the following command:
   ```bash
   docker build --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) -t workbench-docker .
   ```
2. **Run the Docker Container**: Execute a migration task using the following command:
   ```bash
   docker run -it --rm --network="host" \
       -v .:/workbench \
       -v /path/to/your/tmp:/tmp \
       -v /path/to/your/files:/mnt/data/local \
       --name update_existing_objects workbench-docker \
       bash -lc "./workbench --config /workbench/prod/update_islandora_objects.yml --check"
   ```
3. **Verify**: Ensure that:
   - No permission errors occur.
   - Logs are correctly written to the `/workbench/workbench.log`.
   - The container interacts correctly with the mounted directories.

Include any `.yml` configuration files and CSV data necessary for testing. Unit or integration tests should be run if applicable.

## Interested Parties

> @mjordan, @maintainers

---

## Checklist

* [x] Before opening this PR, have you opened an issue explaining what you want to do?
* [ ] Have you included some configuration and/or CSV files useful for testing this PR?
* [ ] Have you written unit or integration tests if applicable?
* [ ] Does the code added in this PR require a version of Python that is higher than the current minimum version?
* [ ] If the changes in this PR require an additional Python library, have you included it in `setup.py`?
* [ ] If the changes in this PR add a new configuration option, have you provided a default for when the option is not present in the .yml file?

### CODE REVIEW

**Comment by mjordan** [comment]
@DonRichards `docker build --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) -t workbench-docker .` built without error, and I was able to run a Workbench task using `docker run`. Is it expected that `docker run` will only work within `islandora_workbench`? If so I think this is ready to merge. I tried running my `docker run` command outside of `islandora_workbench` and it didn't work - is that normal?

**Comment by DonRichards** [comment]
Yes and no. It's copying the files in but you could replace the period in this `-v .:/workbench` with the workbench directory and that should be fine.

**Comment by DonRichards** [comment]
I might need to add that to the docs since you've asked.

**Comment by mjordan** [comment]
Might be a good idea. I assumed that the image could be used from anywhere, in other words that it was portable and even sharable. I guess one overall question that might need to be answered in the docs is why someone want to use a Docker image for Workbench in the first place, if not to avoid local installs of Python and the required libraries.

**Comment by mjordan** [comment]
@DonRichards Unless you have any additional changes to the Dockerfile I can merge this now and we can fix up any docs after that. Is that OK?

**Comment by DonRichards** [comment]
I don't have any changes for the dockerfile, yeah. Just the docs need to be updated.

**Pull request merged**
