### PR TITLE
Issue 292

### PR DESCRIPTION
**Pull request by seth-shaw-asu**
## Link to Github issue or other discussion

#292

## What does this PR do?

Adds an EntityReferenceRevisions field which is used to create paragraph values.

Note: it also includes https://github.com/mjordan/islandora_workbench/pull/617 which was necessary for my site to work.

## How to test / verify this PR?

- Install the Paragraphs module
- create a paragraph type and a field on your content type referencing it
- add the necessary configuration as described in https://github.com/mjordan/islandora_workbench_docs/pull/7
- add values to your CSV and run the add, update, and export tasks.

## Interested Parties

@mjordan

---

## Checklist

* [:heavy_check_mark:] Before opening this PR, have you opened an issue explaining what you want to to do?
* [:heavy_check_mark:] Have you run `pycodestyle --show-source --show-pep8 --ignore=E402,W504 --max-line-length=200 yourfile.py`? 
* [See the linked documentation PR] Have you included same configuration and/or CSV files useful for testing this PR?
* [ No yet; I need to learn how. ] Have you written unit or integration tests if applicable?
* [ No ] Does the code added in this PR require a version of Python that is higher than the current minimum version?
* [ N/A ] If the changes in this PR require an additional Python library, have you included it in `setup.py`?
* [ N/A ] If the changes in this PR add a new configuration option, have you provided a default for when the option is not present in the .yml file?

### CODE REVIEW

**Comment by mjordan** [comment]
@seth-shaw-asu I'll text #617 separately but, to clarify, if I merge this PR, #617 will also be merged - is that correct?

**Comment by seth-shaw-asu** [comment]
Yes, this PR would supersede #617.

**Comment by seth-shaw-asu** [comment]
But it is fine if you want to do them separately. It should still merge cleanly. If not, I can sync my branch.

**Comment by mjordan** [comment]
@seth-shaw-asu nice work! Tested and works as advertised:

* new handling of "published" works (I will update docs)
* am able to create nodes with paragraph fields, and update them, both using repeated value fields.

Couple things:

* in addition to the Paragraphs module, users will also need to enable the paragraphs_types_permissions module
* we need to add (can later) `--config` validation of the Paragraph fieldnames and content
* I couldn't get repeated/multivalued field in the Paragraph entities to work. I assume that's normal at this point; if so, we can look into adding that capability later.

I'm happy to merge is as is and move on from there!

**Comment by seth-shaw-asu** [comment]
> * in addition to the Paragraphs module, users will also need to enable the paragraphs_types_permissions module

Yes, I should update https://github.com/mjordan/islandora_workbench_docs/pull/7 to address that.

> * I couldn't get repeated/multivalued field in the Paragraph entities to work. I assume that's normal at this point; if so, we can look into adding that capability later.

I hadn't even considered that; it wasn't in our use-case. That would add a third layer of delimiter....

> * I wasn't expecting to see node fieldnames that reference paragraphs be top-level entries in the config file (but perhaps I should have been given [your examples in 292](https://github.com/mjordan/islandora_workbench/issues/292#issuecomment-1563167198)). I was expecting them to be grouped under a parent key like `paragraph_fields` (e.g. as shown [here](https://github.com/mjordan/islandora_workbench/issues/292#issuecomment-879147033)). I guess this is OK, but:
>   
>   * I wonder if we should be thinking about extending paragpraphs to media (for example), and how that might be represented in the config file. For example, if we used `paragraph_fields` as the top-level key, `paragraph_type = config.get(field_name, {}).get('type')` would become `paragraph_type = config.get('paragraph_fields').get(field_name, {}).get('type')`. If we separated nodes and media into second-level keys, it would become `paragraph_type = config.get('paragraph_fields').get('nodes').get(field_name, {}).get('type')`.
>   * It would assist `--check` validation by making the fields that are part of paragraphs unambiguously identified, making it easier to validate that those fields are indeed part of the "type"d paragraph.

Using `paragraph_fields` as the top-level key seems reasonable to me. I can do that refactor before we merge this PR.

**Comment by seth-shaw-asu** [comment]
> Three levels of subdelimiting structured CSV strings seems like going to far... so I am happy to leave the "repeated/multivalued field in the Paragraph entities" out for now until someone wants to tackle it in the future. We can document this known deficiency.

Agreed.

> If you have the time to add the `paragraph_fields` config structure though, I'd appreciate it! Is what I have in mind clear enough or would some examples be helpful?

Yes, I'm working *extra* remote this week, but I should be able to do the refactor early next week and update the PR. I *think* I understand what you're suggesting, e.g.

```yml
paragraph_fields:
  field_full_title:
    type: complex_title
    field_order:
      - field_main_title
      - field_subtitle
    field_delimiter: ':'
    subdelimiter: '|'
  field_another_paragraph_field:
...
```

But I always appreciate examples!

**Comment by mjordan** [comment]
I was thinking we should subdivide by entity types, so like:

```
paragraph_fields:
  node:
     field_full_title:
      type: complex_title
      field_order:
        - field_main_title
        - field_subtitle
      field_delimiter: ':'
      subdelimiter: '|'
    field_another_paragraph_field:
       [...]
  media:
    [...]
...

but that might be overkill. Would you ever need to disinguish between fields on a node bundle and a field with the same name on a media bundle? Doing so might make `--check` validation easier since Workbench would know unambiguously where to look when validating the field configs though.

**Comment by seth-shaw-asu** [comment]
@mjordan, I just pushed a commit to use the new config structure you recommended.

**Comment by mjordan** [comment]
@seth-shaw-asu While testing this updated branch I'm getting the following error:

```
mark@mark-XPS-9320:/tmp/islandora_workbench$ ./workbench --config issue_292.yml
OK, connection to Drupal at https://islandora.traefik.me verified.
"Create" task started using config file issue_292.yml.
"nodes_only" option in effect. No media will be created.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /tmp/islandora_workbench/./workbench:1920 in <module>                                            │
│                                                                                                  │
│   1917                                                                                           │
│   1918 try:                                                                                      │
│   1919 │   if config['task'] == 'create':                                                        │
│ ❱ 1920 │   │   create()                                                                          │
│   1921 │   if config['task'] == 'update':                                                        │
│   1922 │   │   update()                                                                          │
│   1923 │   if config['task'] == 'delete':                                                        │
│                                                                                                  │
│ /tmp/islandora_workbench/./workbench:203 in create                                               │
│                                                                                                  │
│    200 │   │   │                                                                                 │
│    201 │   │   │   # Assemble Drupal field structures for entity reference fields from CSV data  │
│    202 │   │   │   # Entity reference fields (taxonomy_term and node).                           │
│ ❱  203 │   │   │   if field_definitions[custom_field]['field_type'] == 'entity_reference':       │
│    204 │   │   │   │   entity_reference_field = workbench_fields.EntityReferenceField()          │
│    205 │   │   │   │   node = entity_reference_field.create(config, field_definitions, node, ro  │
│    206                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'field_pr_292_node_field'
```

I'm using the following config:

```yaml
task: create
host: https://islandora.traefik.me
username: admin
password: password
input_csv: issue_292.csv
standalone_media_url: true
nodes_only: true

paragraph_fields:
  node:
    field_pr_292_node_field:
      type: pr_292_test_paragraph_type
      field_order:
        - field_pr_292_paragraph_field_1
        - field_pr_292_paragraph_field_2
      field_delimter: ':'
      field_subdelimter: '|'
```

with the following CSV:

```
published,file,id,title,field_model,field_pr_292_node_field
,IMG_1410.tif,01,Small boats in Havana Harbour,http://purl.org/coar/resource_type/c_c513,Meow:mix@cat.com|Purr:janeway@cat.ca|Yawn:mjordan@sfu.ca
1,IMG_2549.jp2,02,Manhatten Island,http://purl.org/coar/resource_type/c_c513,
```

Is my config formatted correctly?

**Comment by mjordan** [comment]
Lol, I don't have any Paragraphs configured. I must have rebuilt my ISLE since last testing. Please ignore the above (I'll delete when I have my Paragraphs back....). Sorry!

**Pull request merged**
