### PR TITLE
Convert int to string to avoid errors with requests

### PR DESCRIPTION
**Pull request by aOelschlager**
## Link to Github issue or other discussion

> [Issue #661](https://github.com/mjordan/islandora_workbench/issues/661)

## What does this PR do?

> Fixes string literal error for term_id in update_terms.

## What changes were made?

> Converts int returned by find_term_in_vocab to a string. This was causing errors in the requests because an int was being used in string concatenations.

## How to test / verify this PR?

> <blockquote>
<p dir="auto">To test, you need a csv file with term_id. All other columns are the same as what you would use for create_terms, however, term_name is not used as a lookup value for the term id and only used if you want to change the term name. To change the parent reference to root, value must be 0. The configuration file needs the task update_terms and vocab_id. The term_id and parent can either be string or numeric. The sample data below updates Notated movement term''s reference from Notated music to Mixed Material in the resource types vocabulary.</p>
</blockquote>

<p dir="auto">Sample Data:</p>

term_id | parent
-- | -- 
Notated movement | Mixed Material

<p dir="auto">Sample Configuration File:</p>
<p dir="auto">task: update_terms<br>
host: "<a href="https://islandora.traefik.me" rel="nofollow">https://islandora.traefik.me</a>"<br>
username:<br>
password:<br>
input_dir: update<br>
input_csv: update.csv<br>
vocab_id: resource_types</p>

## Interested Parties

> _**Replace this text** - name some folks who may be interested, or, if unsure, @mjordan_

---

## Checklist

* [ X ] Before opening this PR, have you opened an issue explaining what you want to to do?
* [ X ] Have you run `pycodestyle --show-source --show-pep8 --ignore=E402,W504 --max-line-length=200 yourfile.py`? 
* [ X ] Have you included some configuration and/or CSV files useful for testing this PR?
* [ No ] Have you written unit or integration tests if applicable?
* [ No ] Does the code added in this PR require a version of Python that is higher than the current minimum version?
* [ NA ] If the changes in this PR require an additional Python library, have you included it in `setup.py`?
* [ NA ] If the changes in this PR add a new configuration option, have you provided a default for when the option is not present in the .yml file?

### CODE REVIEW

**Comment by mjordan** [comment]
I see the why taxonomy term fields are not updating. There's a section of code (https://github.com/mjordan/islandora_workbench/blob/main/workbench_utils.py#L777-L780) that I missed adding to the lower-down block that handles taxonomy_term entities. You'll want to add it at https://github.com/mjordan/islandora_workbench/blob/main/workbench_utils.py#L840. Sorry about that!

**Comment by hassanelsheikha** [comment]
Hi @mjordan and @aOelschlager. So sorry to keep you waiting. I tested it just now and it works perfect, thank you so much!

**Comment by mjordan** [comment]
Super, thanks for your patience and for reporting this. I'll merge and we'll get some documentation together as soon as possible.

**Comment by mjordan** [comment]
Passed @hassanelsheikha's smoke test, merging.

**Pull request merged**
