### PR TITLE
Add requirement on python-magic-bin.

### PR DESCRIPTION
**Pull request by jordandukart**

### CODE REVIEW

**Comment by jordandukart** [comment]
As referenced in https://github.com/mjordan/islandora_workbench/issues/238

**Review by mjordan — CHANGES_REQUESTED** [review]
On Ubuntu 18.04, setuptools couldn't find `python-magic-bin`, and `pip3 install python-magic-bin` also couldn't install it (not surprising since setuptools uses pip, I think).

`python-magic` installs reliably, as in:  

```
install_requires=['requests>=2.22,<3', 'ruamel.yaml', 'progress_bar', 'openpyxl', 'python-magic']
```
I'd like to go with a version of `python-magic` that installs most reliably on most platforms. Would you mind installing the non-bin version of `python-magic` on your platform? If that works, let's go with that. If not, I'll investigate further.

**Comment by jordandukart** [comment]
On 11.2.2 macOS:

```
tophat:islandora_workbench tophat$ bin/pip3.9 install .
WARNING: The directory '/Users/tophat/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /Users/tophat/islandora_workbench
Collecting requests<3,>=2.22
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 1.4 MB/s 
Collecting ruamel.yaml
  Downloading ruamel.yaml-0.16.13-py2.py3-none-any.whl (111 kB)
     |████████████████████████████████| 111 kB 2.2 MB/s 
Collecting progress_bar
  Downloading progress_bar-8.tar.gz (5.2 kB)
Collecting openpyxl
  Downloading openpyxl-3.0.6-py2.py3-none-any.whl (242 kB)
     |████████████████████████████████| 242 kB 9.9 MB/s 
Collecting python-magic
  Downloading python_magic-0.4.22-py2.py3-none-any.whl (12 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 21.1 MB/s 
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 18.7 MB/s 
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.3-py2.py3-none-any.whl (137 kB)
     |████████████████████████████████| 137 kB 17.9 MB/s 
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 22.1 MB/s 
Collecting et-xmlfile
  Downloading et_xmlfile-1.0.1.tar.gz (8.4 kB)
Collecting jdcal
  Downloading jdcal-1.4.1-py2.py3-none-any.whl (9.5 kB)
Collecting ruamel.yaml.clib>=0.1.2
  Downloading ruamel.yaml.clib-0.2.2-cp39-cp39-macosx_10_9_x86_64.whl (156 kB)
     |████████████████████████████████| 156 kB 21.7 MB/s 
Building wheels for collected packages: Islandora-Workbench, et-xmlfile, progress-bar
  Building wheel for Islandora-Workbench (setup.py) ... done
  Created wheel for Islandora-Workbench: filename=Islandora_Workbench-master-py3-none-any.whl size=2192 sha256=0b395b9afd10382bedab7c817cf9197d60446068568a6b3f724a8e6bc8fabe7e
  Stored in directory: /private/var/folders/72/7ql22bqd4jq6c2v063q0rv_40000gn/T/pip-ephem-wheel-cache-y8g4zr8r/wheels/db/87/2a/5bd06e02b644e24d56ed280ecbf7ceb96d9aee5472b99a6585
  WARNING: Built wheel for Islandora-Workbench is invalid: Metadata 1.2 mandates PEP 440 version, but 'master' is not
  Building wheel for et-xmlfile (setup.py) ... done
  Created wheel for et-xmlfile: filename=et_xmlfile-1.0.1-py3-none-any.whl size=8913 sha256=783d96df84a7e871e06a9565b72a310855d29f331698d3cc60df72564de089cb
  Stored in directory: /private/var/folders/72/7ql22bqd4jq6c2v063q0rv_40000gn/T/pip-ephem-wheel-cache-y8g4zr8r/wheels/bb/9b/ff/8fdf015c95a57224237bf88fbb9e45237cbe8177213bc13732
  Building wheel for progress-bar (setup.py) ... done
  Created wheel for progress-bar: filename=progress_bar-8-py3-none-any.whl size=5587 sha256=888dceef72a681de2ca452ac8f57042acff8d5f9966725566fce02bf2e9f3365
  Stored in directory: /private/var/folders/72/7ql22bqd4jq6c2v063q0rv_40000gn/T/pip-ephem-wheel-cache-y8g4zr8r/wheels/33/ff/ce/6584daa8701544b76a2d1292e014bf91fd2fb5cbe6c35ad597
Successfully built et-xmlfile progress-bar
Failed to build Islandora-Workbench
Installing collected packages: urllib3, ruamel.yaml.clib, jdcal, idna, et-xmlfile, chardet, certifi, ruamel.yaml, requests, python-magic, progress-bar, openpyxl, Islandora-Workbench
    Running setup.py install for Islandora-Workbench ... done
  DEPRECATION: Islandora-Workbench was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Successfully installed Islandora-Workbench-master certifi-2020.12.5 chardet-4.0.0 et-xmlfile-1.0.1 idna-2.10 jdcal-1.4.1 openpyxl-3.0.6 progress-bar-8 python-magic-0.4.22 requests-2.25.1 ruamel.yaml-0.16.13 ruamel.yaml.clib-0.2.2 urllib3-1.26.3
tophat:islandora_workbench tophat$ bin/python3.9 workbench
Traceback (most recent call last):
  File "/Users/tophat/islandora_workbench/workbench", line 16, in <module>
    from workbench_utils import *
  File "/Users/tophat/islandora_workbench/workbench_utils.py", line 18, in <module>
    import magic
  File "/Users/tophat/islandora_workbench/lib/python3.9/site-packages/magic/__init__.py", line 210, in <module>
    libmagic = loader.load_lib()
  File "/Users/tophat/islandora_workbench/lib/python3.9/site-packages/magic/loader.py", line 39, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```

**Comment by mjordan** [comment]
Thanks. So it looks like `python-magic` installed yet `import magic` is looking for `libmagic`.... @ajstanley can you comment on this since you seem to have everything running on your Mac?

**Comment by mjordan** [comment]
If we can't get this library to install cleanly on multiple platforms, we might be able to get the downloaded file's MIME type from the GET requests's `Content-Type` header, for example as in https://github.com/mjordan/islandora_workbench/blob/main/scripts/get_islandora_7_content.py#L165. That assumes all servers (Islandora and non-Islandora) provide that header in their response but it's pretty standard.

**Comment by ajstanley** [comment]
I just tried this on an Ubuntu 18 box.
  ```
vagrant@islandora8:/var/www/html/drupal/web/sites/default/files/2020-09$ sudo pip3 install python-magic
  Collecting python-magic
    Downloading https://files.pythonhosted.org/packages/ba/7c/1d1d4bdda29bfec662b9b50951dee2dddf7747d3cbf7777f3d1c63372bd0/python_magic-0.4.22-py2.py3-none-any.whl
  Installing collected packages: python-magic
  Successfully installed python-magic-0.4.22
  vagrant@islandora8:/var/www/html/drupal/web/sites/default/files/2020-09$ python3
  Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
  [GCC 8.4.0] on linux
  Type "help", "copyright", "credits" or "license" for more information.
  >>> import magic
  >>> mime = magic.from_file('./56-Thumbnail Image.png', mime=True)
  >>> mime
  'image/png'
```
So, it all looks good to me.  I don't have a windows box to check on though.

**Comment by mjordan** [comment]
@ajstanley do you run Workbench on your Mac? Seems that `pip3 install python-magic` doesn't work for @jordandukart, but `pip3 install python-magic-binary` does. On Ubuntu, `pip3 install python-magic-binary` doesn't work for me. Trying to find a way to install this library on both (I can test Windows once we get it working on those two).

**Comment by ajstanley** [comment]
I'm seeing the same.  I just tried installing python-magic on my backup mac, and I saw the same weirdness.  Uninstalling python-magic, then installing python-magic-bin did the trick.

pip3 install python-magic-bin fails on my vagrant box.

I'll muck about with os.uname() to throw some conditionals in setup.py.

**Comment by mjordan** [comment]
Gross. The more I think about this I'm leaning toward switching to getting the MIME type from the HTTP response header. That way, the problematic library wouldn't be necessary.

**Comment by mjordan** [comment]
@jordandukart any thoughts on moving to using the `Content-Type` header as the source of the MIME type of the downloded file? Ever see any HTTP responses that don't include it?

**Comment by ajstanley** [comment]
The fact is, the sniffer only kicks in when the asset is missing an extension.  That's pretty rare in the non-Islandora 7 world.

**Comment by mjordan** [comment]
Right. And we know that Islandora 7 does return a Content-Type header. I say we abandon the problematic library switch over to using that. I'm happy to do that work.

**Comment by ajstanley** [comment]
Agreed.  Too bad - the magic library works really well.  I was told that once Y2K was solved we'd leave all this behind us.

**Comment by DonRichards** [comment]
What worked for me on OSX is this. Obviously it's already been mentioned but I thought another example would be useful to someone. 

```shell
$ python3 -m pip install setuptools filemagic libmagic
```

**Comment by DonRichards** [comment]
@ajstanley I'd avoid running pip install as sudo if you don't need to. You could always encapsulate everything within Python's [Virtual Environments](https://docs.python-guide.org/dev/virtualenvs/).

**Comment by mjordan** [comment]
Guys, I would like to avoid installing that library completely and get the file's MIMEtype from the HTTP response. Same functionality, a lot better installer experience across OSs. I can do any required fixes to the code but might ask you to test. That sound like a plan?

**Comment by ajstanley** [comment]
I'm with Mark on this.  I really like the magic library, but if tomfoolery is required to install we're better off with grabbing the mimetype from the HTTP response.

**Comment by mjordan** [comment]
OK, I removed the dependency on the `magic` library and creating media from remote files with and without extensions are working:

``
file,id,title,field_model
http://localhost:8000/islandora/object/testing%3A23/datastream/OBJ/download,01,7000 Miles Through BC,25
http://localhost:8000/islandora/object/testing%3A30/datastream/OBJ/download,02,Bowen Island Inn,25
http://localhost:8000/sites/default/files/edcartoons_469.jpg,02,Cartoon 1,25
http://localhost:8000/sites/default/files/edcartoons_842.jpg,02,Cartoon 2,25
``

I've merged this into `main`. @jordandukart please pull in updates from `main`, try to reinstall, and let me know if you hit any problems.

**Comment by jordandukart** [comment]
Works for me @mjordan, closing.

**Pull request closed without merging**
