### PR TITLE
Add support for media entity reference fields.

### PR DESCRIPTION
**Pull request by rosiel**
## What does thie PR do?

Enables entity reference fields that refer to media (by mid)

## What changes were made?

four lines added parallel to  how this works for nodes

## How to test / veryify this PR?

Does it work?

## Interested Parties

Hope you're not looking at this on vacation @mjordan

---

## Checklist

* [ ] Have you run `pycodestyle --show-source --show-pep8 --ignore=E402,W504 --max-line-length=200 yourfile.py`? 
* [ ] Have you included same configuration and/or CSV files useful for testing this PR?
* [ ] Have you written unit or integration tests if applicable?
* [ ] If the changes in this PR require an addiional Python library, have you included it in `setup.py`?
* [ ] If the changes in this PR add a new configuration option, have you provided a default for when the option is not present in the .yml file?
* [ ] Did the PR receive at least one approval from a committer, and all issues raised have been addressed?

### CODE REVIEW

**Comment by mjordan** [comment]
@rosiel thanks for this. To test, would I just create a media reference field on my Islandora object node and populate my CSV with the media ID?

**Comment by rosiel** [comment]
sorry - yes!

**Comment by mjordan** [comment]
@rosiel works as advertised for `update` tasks. A couple of things for later (or sooner, if you have time):

- It would be good to have `--check` validate that the referenced media exists (this [already happens](https://github.com/mjordan/islandora_workbench/blob/main/workbench_utils.py#L1126) for node references in `field_member_of`). We can add that separately from this PR. I can add that if you want, or if you want to, let me know.
- I'd like to have it also work with `create` tasks since someone will likely ask for it eventually. I don't mind adding that functionality myself later, or, if you have time and capacity, you could.

I'm happy to merge and document this now if you want and we can work out the two items above later.

**Comment by mjordan** [comment]
@rosiel I'd like to merge this to prevent too much divergence between branches. OK to do so? We can follow up on next steps later.

**Comment by rosiel** [comment]
sounds good to me - i'll update the ticket for those two tasks.

**Comment by mjordan** [comment]
Thanks - I've merged this into main. We can open separate PRs for the other work.

**Pull request merged**
